from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from app.answer_render import normalize_operator_answer
from app.config import Settings
from app.models import PipelineResult
from app.one_mcp import OneMcpClient


def build_issue_draft(
    result: PipelineResult,
    *,
    human_approval: str = "pending",
    title_override: str = "",
    body_override: str = "",
) -> dict[str, Any]:
    rec = result.recommendation
    ts = datetime.now(timezone.utc).isoformat()
    summary = normalize_operator_answer(rec.recommended_action)
    title = title_override.strip() or (
        f"[LiveOps] {result.incident_id} · {result.correlation_id[:16]}"
    )
    cite_lines = [
        f"- [{c.title}]({c.url})" for c in rec.citations[:12]
    ] or ["- _(No web citations — run Investigate with Live Sources first)_"]
    hypo = rec.hypotheses[:8]
    facts = rec.observed_facts[:10]
    body = body_override.strip() or _issue_body_markdown(
        incident_summary=summary,
        facts=facts,
        hypotheses=hypo,
        cite_lines=cite_lines,
        risk=rec.risk_level,
        confidence=rec.confidence,
        correlation_id=result.correlation_id,
        session_id=result.session_id,
        youcom_mode=result.youcom_mode,
        providers=result.providers_used,
        human_approval=human_approval,
        not_changed="No production restart, WhatsApp recover, or delete_instance (dry-run).",
        timestamp=ts,
    )
    return {
        "title": title,
        "body": body,
        "labels": ["liveops-incident", "demo"],
        "metadata": {
            "correlation_id": result.correlation_id,
            "session_id": result.session_id,
            "youcom_mode": result.youcom_mode,
            "risk_level": rec.risk_level,
        },
    }


def _issue_body_markdown(
    *,
    incident_summary: str,
    facts: list[str],
    hypotheses: list[str],
    cite_lines: list[str],
    risk: str,
    confidence: float,
    correlation_id: str,
    session_id: str,
    youcom_mode: str,
    providers: list[dict],
    human_approval: str,
    not_changed: str,
    timestamp: str,
) -> str:
    prov_lines = [
        f"- {p.get('role')}: {p.get('provider')} ({p.get('detail', '')})"
        for p in providers[:8]
    ]
    return f"""## Incident summary
{incident_summary}

## Observed facts (live / read-only)
{chr(10).join('- ' + f for f in facts)}

## Model hypotheses _(not verified facts)_
{chr(10).join('- ' + h for h in hypotheses)}

## Web evidence & citations
{chr(10).join(cite_lines)}

## Recommended next steps
See summary above. All actions require human approval; this issue is tracking only.

## Risk & confidence
- **Risk:** {risk}
- **Confidence:** {confidence:.0%}

## What was NOT changed
{not_changed}

## Run metadata
- **correlation_id:** `{correlation_id}`
- **session_id:** `{session_id}`
- **timestamp:** {timestamp}
- **youcom_mode:** {youcom_mode}
- **human_approval:** {human_approval}

## Providers / models this run
{chr(10).join(prov_lines)}

---
_Generated by RalphiIA LiveOps Intelligence (dry-run). No private IPs or secrets included._
"""


async def create_github_incident(
    settings: Settings,
    draft: dict[str, Any],
) -> dict[str, Any]:
    owner = settings.github_repo_owner
    repo = settings.github_repo_name
    if not owner or not repo:
        raise ValueError("Set GITHUB_REPO_OWNER and GITHUB_REPO_NAME in environment")

    title = str(draft.get("title") or "")
    body = str(draft.get("body") or "")
    labels = list(draft.get("labels") or ["liveops-incident"])

    one = OneMcpClient(settings)
    if not one.configured():
        raise ValueError(
            "Set ONE_SECRET (One MCP). GitHub issues are created only via One, not GITHUB_TOKEN."
        )
    out = await one.create_github_issue(owner, repo, title, body, labels=labels)
    if not out.get("ok") or not out.get("html_url"):
        raise RuntimeError(
            "One MCP did not return a GitHub issue URL. "
            f"Connect GitHub in One dashboard. Raw: {str(out)[:400]}"
        )
    return out
